networks:
  portfolio_network:
    name: portfolio_network
    driver: bridge

services:
  portfolio_mongo:
    image: mongo:latest
    container_name: portfolio_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - portfolio_mongo:/data
    networks:
      - portfolio_network

  portfolio_redis:
    image: redis:latest
    container_name: portfolio_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - portfolio_redis:/data
    networks:
      - portfolio_network

  portfolio_api:
    build: .
    image: portfolio_api:v0.0.1
    container_name: portfolio_api
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongodb://portfolio_mongo:27018/portfolio
      - REDIS_URI=redis://portfolio_redis:6380
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    ports:
      - "3001:3001"
    networks:
      - portfolio_network
    depends_on:
      - portfolio_mongo
      - portfolio_redis

volumes:
  portfolio_mongo:
  portfolio_redis:
